### PR TITLE
Merge upstream fixes + go mod change by @tooolbox

### PR DESCRIPTION
**Pull request by knz**
Note: getsentry/raven-go is obsolete and we need to replace it by getsentry/sentry-go. This repo is maintained for compatibility with existing code.

### CODE REVIEW

**Comment by knz** [comment]
@tooolbox can you have a look at this please.
Today it does not build. Please in particular look at PR #1 in this repo and the accompanying commit. We'd prefer if your go module change could avoid using Go's `build` package. Is that possible?

**Comment by tooolbox** [comment]
Thanks! I'll have a look and let you know soon.

**Comment by tooolbox** [comment]
Interesting.  

`build.Default.GOROOT` [calls `runtime.GOROOT()`](https://golang.org/src/go/build/build.go?s=502:3757#L292) which [checks `$GOROOT` from the environment](https://golang.org/src/runtime/extern.go?s=10815:10835#L217) and if it finds nothing it [uses `sys.DefaultGoroot`](https://golang.org/pkg/runtime/internal/sys/#pkg-variables) which is set at linking time.

Using plain-old `sys.DefaultGoroot` might work out, but I don't see that we have that ability.

Also interesting is that it [didn't always work exactly that way](https://go-review.googlesource.com/c/go/+/86835/).

**Comment by tooolbox** [comment]
@knz please check out https://github.com/tooolbox/raven-go/commit/a851f364251b9191fb8ddcacddf4a8fe9492afa9, I guess it can be cherry-picked?.

After looking at this from several angles, I made some changes:
- The legacy behavior (using `appPackagePrefixes`) will be used in pre-1.10.
- For 1.10 and later, if the executing machine's `$GOROOT` is empty (which it should be, these days) then the new behavior will be used which seems to mark things `InApp: true` more liberally.
- For 1.10 and later, if `$GOROOT` is populated, we can't be very certain about excluding stdlib frames, so revert to the old behavior.
- For 1.10 and later, exclude frames that contain `/go/pkg/mod/` as this is an indicator of the Go Modules read-only cache.

A few notes:
- The fix in #1 is only feasible because both `$GOPATH` and `$GOROOT` code begin with `/src/`, whereas in this case the goal is to identify and exclude `$GOROOT` code while keeping some `$GOPATH` code.
- Although `go/build.Default.GOROOT` will assume the value of the executing machine's `$GOROOT`...
    - From what I can tell, `$GOROOT` is not set by much of anyone these days (while `$GOPATH` still lives on in a variety of projects).
    - There isn't a better way to identify stdlib packages.
- I'm not sure why `getsentry/sentry-go` does not make any effort to exclude material in the Go Modules Cache.  They exclude vendored packages, which (these days) is essentially a local version of the Module Cache, so why not the actual Module Cache?  I decided to add this point, although it is based on opinion and subject to change.
- For Go 1.5 and earlier, identifying stdlib packages is very easy because their paths always begin with `/usr/local/go`, no matter what.  I can add support for this if needed.

**Comment by tooolbox** [comment]
@knz I'm also curious how important this particular feature is to your team.  It seems like `sentry-go` fully uses the `go/build` package, so upgrading will not solve this issue; I think it's up to you & your team to decide what behavior you want given the constraints of the problem.

I know this is a little messy but please let me know your thoughts and I can make some tweaks as needed.

**Comment by knz** [comment]
>  I'm also curious how important this particular feature is to your team.

So the reason why this mattered in the past is that this code path is used to distingush "in-app" from "out-of-app" sentry reports, and our bug tracking/filing system use that bit. If we get it wrong (and start getting out-of-app for things that should really be marked as in-app, or vice-versa) we're going to screw up the bug reporting.

If we can get some confidence that this not a problem any more (ie. modern uses of Go in prod systems will prevent sentry from getting it wrong in most cases) then it does not matter; otherwise, I  guess we'll need to fork sentry-go and figure out a replacement mechanism.

**Comment by tooolbox** [comment]
> So the reason why this mattered in the past is that this code path is used to distingush "in-app" from "out-of-app" sentry reports, and our bug tracking/filing system use that bit.

Thanks, that makes sense.

*What, then, do you consider to be in-app?*

This is an important question because it might be handled differently between a $GOPATH project and a Go Modules project.

Generally speaking, I believe we can assume that anything in the standard library would be considered out-of-app.  But what about outside of the standard library?

The approach that `raven-go` takes is to accept a slice of "includePaths," meaning roughly that "these are the path prefixes that we will consider to be in your app".  Any of those paths are fine, unless they're in a vendor folder.  See:

```go
func isInAppFrame(frame StacktraceFrame, appPackagePrefixes []string) bool {
	if frame.Module == "main" {
		return true
	}
  for _, prefix := range appPackagePrefixes {
    if strings.HasPrefix(frame.Module, prefix) && !strings.Contains(frame.Module, "vendor") && !strings.Contains(frame.Module, "third_party") {
      return true
    }
  }
	return false
}
```

This is a more exclusive approach.  Your `main` package gets included, (does that include folders contained within the `main` package?) and then basically only whatever you say that you want.  The way you "say what you want" is generally to call `SetIncludePaths()` on the `raven.DefaultClient` or whatever client you're using.

The [approach that `sentry-go` takes](https://github.com/getsentry/sentry-go/blob/master/stacktrace.go#L234) is to say that *everything* is "in-app" unless it's in the stdlib or in a vendor folder:

```go
func isInAppFrame(frame Frame) bool {
	if strings.HasPrefix(frame.AbsPath, build.Default.GOROOT) ||
		strings.Contains(frame.Module, "vendor") ||
		strings.Contains(frame.Module, "third_party") {
		return false
	}

	return true
}
```

This is more liberal, obviously.

-------------------------------

From reading the source of `cockroachdb/errors` you're not calling [NewStackTrace](https://github.com/getsentry/raven-go/blob/master/stacktrace.go#L94) or anything like that.  You seem to [create an exception](https://github.com/cockroachdb/errors/blob/master/report/report.go#L171), giving it a [premade reportable stacktrace](https://github.com/cockroachdb/errors/blob/master/report/report.go#L43), created by [some magic conversions](https://github.com/cockroachdb/errors/blob/master/withstack/reportable.go#L46) possibly from a `pkg/errors` stacktrace, which ultimately seems to call `parsePrintedStack()` which [sets inApp=true](https://github.com/cockroachdb/errors/blob/master/withstack/reportable.go#L146) and calls `trimPath()` which [uses the `go/build` package](https://github.com/cockroachdb/errors/blob/master/withstack/reportable.go#L102) for path trimming.

This was only a quick skim/dive, maybe you can confirm this is correct?

--------------------------------

Assuming that you are using `cockroachdb/raven-go` in other places besides `cockroachdb/errors`, what approach do you want to use for marking things as in-app?  Do you want the more restrictive style, or the more liberal style?  Does your team typically pass in prefix paths?

I think there's an easy solution not to screw up your bug reporting, but I want to fully understand the constraints.

**Comment by knz** [comment]
> What, then, do you consider to be in-app?

Mostly, only code either in the project's own source dir (this happens to be `pkg/...` in CockroachDB). If possible, also including specific `vendor/` sub-dirs but not all.

Regarding this:

```
		strings.Contains(frame.Module, "vendor") ||
		strings.Contains(frame.Module, "third_party") {
```

I'm not exactly comfortable about these matches because they also match other things like `vendor_foo` or `my_third_party`. I wonder why the match is implemented this way (instead of matching e.g. `/vendor/`)

Finally note that in CockroachDB we have two uses of raven-go (soon sentry-go):

- one to report panics
- one to report errors (including but not limited to errors generated in the `cockroachdb/errors` package, it also includes errors generated by other Go libs via the standard `error`)

It's important that we be able to use the same `raven-go` import for both (to not get duplicated code in the binary) so whatever choice we make here has to work in both cases.

**Comment by tooolbox** [comment]
> Mostly, only code either in the project's own source dir (this happens to be pkg/... in CockroachDB). If possible, also including specific vendor/ sub-dirs but not all.

Okay, that's good info.  I am tracking with everything you're saying, and I have some further questions on that, but first:

When `cockroachdb/errors` formulates a stack trace as in `WithStack()` [it marks *every frame* as in-app](https://github.com/cockroachdb/errors/blob/master/withstack/reportable.go#L146).  So the question is moot for that library.

Can you link to all other integration points where `raven-go` is used by your team?  That's what we need to examine, I think.

**Comment by tooolbox** [comment]
I suppose that since this is a custom implementation, I can simply revert the behavior to the existing version (using appPackagePrefixes) to give your team full control over what paths are in-app.

I will need to look at the tests newly to see how to make that work, but would that overall be an acceptable route?

**Comment by knz** [comment]
It's possible that this is sufficient, yes, however I want to be honest I haven't had much time in the last week to look into this. This week and next are hectic and we may be a bit slow to react. How urgent is this?

**Comment by tooolbox** [comment]
Thanks, appreciated.

It's not urgent per se.  I am using my own fork of `cockroachdb/errors` with Go Module support at the moment, and that is working fine.  My drive here is to land this support in the main repo as a point of durability, continued maintenance, and to promote more usage of the package within the community, as adoption of Go Modules has been very fast from what I have seen.

I will slot in the work on this within the next week or two and ideally have some good news by the time you are freed up.  I appreciate your consistent response and helpfulness!

**Comment by tooolbox** [comment]
Alright @knz so I have this for you: https://github.com/tooolbox/raven-go/commits/raven-roach

This reverts to the old (current) style of checking whether a frame is in your app.  In other words, there are effectively no changes in that respect.  If you want to change the matching of "vendor" and "third_party" packages, I feel that those should be the subject of another issue.

All tests pass, including importing it into another package and running `go test all -short`.

Please let me know if anything else is needed.

**Comment by tooolbox** [comment]
@knz you may still be very busy; do you have an estimate on when you will be able to review this?

I would like to get this wrapped so I can shift off the fork soon.

**Comment by knz** [comment]
I'm actually traveling this week. Next Monday at the latest. Perhaps ping me for certainty
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by knz** [comment]
This looks good to me now.

**Pull request merged**
